from _typeshed import Incomplete
from torch.distributed.nn.jit.templates.remote_module_template import get_remote_module_template as get_remote_module_template

logger: Incomplete
_FILE_PREFIX: str
_TEMP_DIR: Incomplete
INSTANTIATED_TEMPLATE_DIR_PATH: Incomplete

def get_arg_return_types_from_interface(module_interface): ...
def _write(out_path, text) -> None: ...
def _do_instantiate_remote_module_template(generated_module_name, str_dict, enable_moving_cpu_tensors_to_cuda): ...
def instantiate_scriptable_remote_module_template(module_interface_cls, enable_moving_cpu_tensors_to_cuda: bool = True): ...
def instantiate_non_scriptable_remote_module_template(): ...
