def _faulty_tensorpipe_construct_rpc_backend_options_handler(rpc_timeout, init_method, num_worker_threads, messages_to_fail, messages_to_delay, num_fail_sends, **kwargs): ...
def _faulty_tensorpipe_init_backend_handler(store, name, rank, world_size, rpc_backend_options): ...
