from _typeshed import Incomplete

class GLContext:
    """An OpenGL context created via GLFW."""
    _context: Incomplete
    def __init__(self, max_width, max_height) -> None: ...
    def make_current(self) -> None: ...
    def free(self) -> None: ...
    def __del__(self) -> None: ...
