from torch import _C
from torch.onnx._internal import jit_utils

__all__ = ['_grid_sampler', '_affine_grid_generator', 'gelu']

def _grid_sampler(g: jit_utils.GraphContext, input: _C.Value, grid: _C.Value, mode_enum: int, padding_mode_enum: int, align_corners: bool): ...
def _affine_grid_generator(g: jit_utils.GraphContext, theta: _C.Value, size: _C.Value, align_corners: bool): ...
def gelu(g: jit_utils.GraphContext, self: _C.Value, approximate: str = 'none'): ...
