from _typeshed import Incomplete
from torch import _C as _C
from torch.onnx import symbolic_helper as symbolic_helper, symbolic_opset9 as opset9
from torch.onnx._internal import jit_utils as jit_utils, registration as registration

_onnx_symbolic: Incomplete

def aten__is_(g: jit_utils.GraphContext, self, other): ...
@opset9.wrap_logical_op_with_negation
def aten__isnot_(g: jit_utils.GraphContext, self, other): ...
def bernoulli(g: jit_utils.GraphContext, input, p=None, generator=None, out=None): ...
def prim_unchecked_cast(g: jit_utils.GraphContext, self): ...
