from . import UFUNC_HELPERS as UFUNC_HELPERS, UNSUPPORTED_UFUNCS as UNSUPPORTED_UFUNCS
from _typeshed import Incomplete
from astropy.units.core import dimensionless_unscaled as dimensionless_unscaled, unit_scale_converter as unit_scale_converter
from astropy.units.errors import UnitConversionError as UnitConversionError, UnitTypeError as UnitTypeError, UnitsError as UnitsError
from astropy.utils.compat.numpycompat import NUMPY_LT_2_0 as NUMPY_LT_2_0, NUMPY_LT_2_1 as NUMPY_LT_2_1, NUMPY_LT_2_2 as NUMPY_LT_2_2, NUMPY_LT_2_3 as NUMPY_LT_2_3

def _d(unit): ...
def get_converter(from_unit, to_unit):
    """Like Unit.get_converter, except returns None if no scaling is needed,
    i.e., if the inferred scale is unity.
    """
def get_converters_and_unit(f, unit1, unit2): ...
def helper_onearg_test(f, unit): ...
def helper_invariant(f, unit): ...
def helper_square(f, unit): ...
def helper_reciprocal(f, unit): ...

one_half: float
one_third: Incomplete

def helper_sqrt(f, unit): ...
def helper_cbrt(f, unit): ...
def helper_modf(f, unit): ...
def helper__ones_like(f, unit): ...
def helper_dimensionless_to_dimensionless(f, unit): ...
def helper_dimensionless_to_radian(f, unit): ...
def helper_degree_to_radian(f, unit): ...
def helper_radian_to_degree(f, unit): ...
def helper_radian_to_dimensionless(f, unit): ...
def helper_frexp(f, unit): ...
def helper_multiplication(f, unit1, unit2): ...
def helper_division(f, unit1, unit2): ...
def helper_power(f, unit1, unit2): ...
def helper_ldexp(f, unit1, unit2): ...
def helper_copysign(f, unit1, unit2): ...
def helper_heaviside(f, unit1, unit2): ...
def helper_two_arg_dimensionless(f, unit1, unit2): ...
helper_twoarg_invariant = get_converters_and_unit

def helper_twoarg_comparison(f, unit1, unit2): ...
def helper_twoarg_invtrig(f, unit1, unit2): ...
def helper_twoarg_floor_divide(f, unit1, unit2): ...
def helper_divmod(f, unit1, unit2): ...
def helper_clip(f, unit1, unit2, unit3): ...

onearg_test_ufuncs: Incomplete
invariant_ufuncs: Incomplete
dimensionless_to_dimensionless_ufuncs: Incomplete
dimensionless_to_radian_ufuncs: Incomplete
degree_to_radian_ufuncs: Incomplete
radian_to_degree_ufuncs: Incomplete
radian_to_dimensionless_ufuncs: Incomplete
two_arg_dimensionless_ufuncs: Incomplete
twoarg_invariant_ufuncs: Incomplete
twoarg_comparison_ufuncs: Incomplete
twoarg_invtrig_ufuncs: Incomplete
