from .transform import BaseTransform, CompositeTransform
from _typeshed import Incomplete

__all__ = ['BaseStretch', 'LinearStretch', 'SqrtStretch', 'PowerStretch', 'PowerDistStretch', 'SquaredStretch', 'LogStretch', 'AsinhStretch', 'SinhStretch', 'HistEqStretch', 'ContrastBiasStretch', 'CompositeStretch']

class BaseStretch(BaseTransform):
    """
    Base class for the stretch classes, which when called with an array
    of values in the range [0:1], returns an transformed array of values
    also in the range [0:1].
    """
    @property
    def _supports_invalid_kw(self): ...
    def __add__(self, other): ...
    def __call__(self, values, clip: bool = True, out: Incomplete | None = None) -> None:
        """
        Transform values using this stretch.

        Parameters
        ----------
        values : array-like
            The input values, which should already be normalized to the
            [0:1] range.
        clip : bool, optional
            If `True` (default), values outside the [0:1] range are
            clipped to the [0:1] range.
        out : ndarray, optional
            If specified, the output values will be placed in this array
            (typically used for in-place calculations).

        Returns
        -------
        result : ndarray
            The transformed values.
        """
    @property
    def inverse(self) -> None:
        """A stretch object that performs the inverse operation."""

class LinearStretch(BaseStretch):
    """
    A linear stretch with a slope and offset.

    The stretch is given by:

    .. math::
        y = slope * x + intercept

    Parameters
    ----------
    slope : float, optional
        The ``slope`` parameter used in the above formula.  Default is 1.
    intercept : float, optional
        The ``intercept`` parameter used in the above formula.  Default is 0.
    """
    slope: Incomplete
    intercept: Incomplete
    def __init__(self, slope: int = 1, intercept: int = 0) -> None: ...
    def __call__(self, values, clip: bool = True, out: Incomplete | None = None): ...
    @property
    def inverse(self):
        """A stretch object that performs the inverse operation."""

class SqrtStretch(BaseStretch):
    """
    A square root stretch.

    The stretch is given by:

    .. math::
        y = \\sqrt{x}
    """
    @property
    def _supports_invalid_kw(self): ...
    def __call__(self, values, clip: bool = True, out: Incomplete | None = None, invalid: Incomplete | None = None):
        '''
        Transform values using this stretch.

        Parameters
        ----------
        values : array-like
            The input values, which should already be normalized to the
            [0:1] range.
        clip : bool, optional
            If `True` (default), values outside the [0:1] range are
            clipped to the [0:1] range.
        out : ndarray, optional
            If specified, the output values will be placed in this array
            (typically used for in-place calculations).
        invalid : None or float, optional
            Value to assign NaN values generated by this class.  NaNs in
            the input ``values`` array are not changed.  This option is
            generally used with matplotlib normalization classes, where
            the ``invalid`` value should map to the matplotlib colormap
            "under" value (i.e., any finite value < 0).  If `None`, then
            NaN values are not replaced.  This keyword has no effect if
            ``clip=True``.

        Returns
        -------
        result : ndarray
            The transformed values.
        '''
    @property
    def inverse(self):
        """A stretch object that performs the inverse operation."""

class PowerStretch(BaseStretch):
    """
    A power stretch.

    The stretch is given by:

    .. math::
        y = x^a

    Parameters
    ----------
    a : float
        The power index (see the above formula).  ``a`` must be greater
        than 0.
    """
    @property
    def _supports_invalid_kw(self): ...
    a: Incomplete
    def __init__(self, a) -> None: ...
    def __call__(self, values, clip: bool = True, out: Incomplete | None = None, invalid: Incomplete | None = None):
        '''
        Transform values using this stretch.

        Parameters
        ----------
        values : array-like
            The input values, which should already be normalized to the
            [0:1] range.
        clip : bool, optional
            If `True` (default), values outside the [0:1] range are
            clipped to the [0:1] range.
        out : ndarray, optional
            If specified, the output values will be placed in this array
            (typically used for in-place calculations).
        invalid : None or float, optional
            Value to assign NaN values generated by this class.  NaNs in
            the input ``values`` array are not changed.  This option is
            generally used with matplotlib normalization classes, where
            the ``invalid`` value should map to the matplotlib colormap
            "under" value (i.e., any finite value < 0).  If `None`, then
            NaN values are not replaced.  This keyword has no effect if
            ``clip=True``.

        Returns
        -------
        result : ndarray
            The transformed values.
        '''
    @property
    def inverse(self):
        """A stretch object that performs the inverse operation."""

class PowerDistStretch(BaseStretch):
    """
    An alternative power stretch.

    The stretch is given by:

    .. math::
        y = \\frac{a^x - 1}{a - 1}

    Parameters
    ----------
    a : float, optional
        The ``a`` parameter used in the above formula.  ``a`` must be
        greater than or equal to 0, but cannot be set to 1.  Default is
        1000.
    """
    a: Incomplete
    def __init__(self, a: float = 1000.0) -> None: ...
    def __call__(self, values, clip: bool = True, out: Incomplete | None = None): ...
    @property
    def inverse(self):
        """A stretch object that performs the inverse operation."""

class InvertedPowerDistStretch(BaseStretch):
    """
    Inverse transformation for
    `~astropy.image.scaling.PowerDistStretch`.

    The stretch is given by:

    .. math::
        y = \\frac{\\log(y (a-1) + 1)}{\\log a}

    Parameters
    ----------
    a : float, optional
        The ``a`` parameter used in the above formula.  ``a`` must be
        greater than or equal to 0, but cannot be set to 1.  Default is
        1000.
    """
    a: Incomplete
    def __init__(self, a: float = 1000.0) -> None: ...
    def __call__(self, values, clip: bool = True, out: Incomplete | None = None): ...
    @property
    def inverse(self):
        """A stretch object that performs the inverse operation."""

class SquaredStretch(PowerStretch):
    """
    A convenience class for a power stretch of 2.

    The stretch is given by:

    .. math::
        y = x^2
    """
    def __init__(self) -> None: ...
    @property
    def inverse(self):
        """A stretch object that performs the inverse operation."""

class LogStretch(BaseStretch):
    """
    A log stretch.

    The stretch is given by:

    .. math::
        y = \\frac{\\log{(a x + 1)}}{\\log{(a + 1)}}

    Parameters
    ----------
    a : float
        The ``a`` parameter used in the above formula.  ``a`` must be
        greater than 0.  Default is 1000.
    """
    @property
    def _supports_invalid_kw(self): ...
    a: Incomplete
    def __init__(self, a: float = 1000.0) -> None: ...
    def __call__(self, values, clip: bool = True, out: Incomplete | None = None, invalid: Incomplete | None = None):
        '''
        Transform values using this stretch.

        Parameters
        ----------
        values : array-like
            The input values, which should already be normalized to the
            [0:1] range.
        clip : bool, optional
            If `True` (default), values outside the [0:1] range are
            clipped to the [0:1] range.
        out : ndarray, optional
            If specified, the output values will be placed in this array
            (typically used for in-place calculations).
        invalid : None or float, optional
            Value to assign NaN values generated by this class.  NaNs in
            the input ``values`` array are not changed.  This option is
            generally used with matplotlib normalization classes, where
            the ``invalid`` value should map to the matplotlib colormap
            "under" value (i.e., any finite value < 0).  If `None`, then
            NaN values are not replaced.  This keyword has no effect if
            ``clip=True``.

        Returns
        -------
        result : ndarray
            The transformed values.
        '''
    @property
    def inverse(self):
        """A stretch object that performs the inverse operation."""

class InvertedLogStretch(BaseStretch):
    """
    Inverse transformation for `~astropy.image.scaling.LogStretch`.

    The stretch is given by:

    .. math::
        y = \\frac{e^{y \\log{a + 1}} - 1}{a} \\\\\n        y = \\frac{e^{y} (a + 1) - 1}{a}

    Parameters
    ----------
    a : float, optional
        The ``a`` parameter used in the above formula.  ``a`` must be
        greater than 0.  Default is 1000.
    """
    a: Incomplete
    def __init__(self, a) -> None: ...
    def __call__(self, values, clip: bool = True, out: Incomplete | None = None): ...
    @property
    def inverse(self):
        """A stretch object that performs the inverse operation."""

class AsinhStretch(BaseStretch):
    """
    An asinh stretch.

    The stretch is given by:

    .. math::
        y = \\frac{{\\rm asinh}(x / a)}{{\\rm asinh}(1 / a)}.

    Parameters
    ----------
    a : float, optional
        The ``a`` parameter used in the above formula. The value of this
        parameter is where the asinh curve transitions from linear to
        logarithmic behavior, expressed as a fraction of the normalized
        image. The stretch becomes more linear as the ``a`` value is
        increased. ``a`` must be greater than 0. Default is 0.1.
    """
    a: Incomplete
    def __init__(self, a: float = 0.1) -> None: ...
    def __call__(self, values, clip: bool = True, out: Incomplete | None = None): ...
    @property
    def inverse(self):
        """A stretch object that performs the inverse operation."""

class SinhStretch(BaseStretch):
    """
    A sinh stretch.

    The stretch is given by:

    .. math::
        y = \\frac{{\\rm sinh}(x / a)}{{\\rm sinh}(1 / a)}

    Parameters
    ----------
    a : float, optional
        The ``a`` parameter used in the above formula. The stretch
        becomes more linear as the ``a`` value is increased. ``a`` must
        be greater than 0. Default is 1/3.
    """
    a: Incomplete
    def __init__(self, a=...) -> None: ...
    def __call__(self, values, clip: bool = True, out: Incomplete | None = None): ...
    @property
    def inverse(self):
        """A stretch object that performs the inverse operation."""

class HistEqStretch(BaseStretch):
    """
    A histogram equalization stretch.

    Parameters
    ----------
    data : array-like
        The data defining the equalization.
    values : array-like, optional
        The input image values, which should already be normalized to
        the [0:1] range.
    """
    data: Incomplete
    values: Incomplete
    def __init__(self, data, values: Incomplete | None = None) -> None: ...
    def __call__(self, values, clip: bool = True, out: Incomplete | None = None): ...
    @property
    def inverse(self):
        """A stretch object that performs the inverse operation."""

class InvertedHistEqStretch(BaseStretch):
    """
    Inverse transformation for `~astropy.image.scaling.HistEqStretch`.

    Parameters
    ----------
    data : array-like
        The data defining the equalization.
    values : array-like, optional
        The input image values, which should already be normalized to
        the [0:1] range.
    """
    data: Incomplete
    values: Incomplete
    def __init__(self, data, values: Incomplete | None = None) -> None: ...
    def __call__(self, values, clip: bool = True, out: Incomplete | None = None): ...
    @property
    def inverse(self):
        """A stretch object that performs the inverse operation."""

class ContrastBiasStretch(BaseStretch):
    """
    A stretch that takes into account contrast and bias.

    The stretch is given by:

    .. math::
        y = (x - {\\rm bias}) * {\\rm contrast} + 0.5

    and the output values are clipped to the [0:1] range.

    Parameters
    ----------
    contrast : float
        The contrast parameter (see the above formula).

    bias : float
        The bias parameter (see the above formula).
    """
    contrast: Incomplete
    bias: Incomplete
    def __init__(self, contrast, bias) -> None: ...
    def __call__(self, values, clip: bool = True, out: Incomplete | None = None): ...
    @property
    def inverse(self):
        """A stretch object that performs the inverse operation."""

class InvertedContrastBiasStretch(BaseStretch):
    """
    Inverse transformation for ContrastBiasStretch.

    Parameters
    ----------
    contrast : float
        The contrast parameter (see
        `~astropy.visualization.ConstrastBiasStretch).

    bias : float
        The bias parameter (see
        `~astropy.visualization.ConstrastBiasStretch).
    """
    contrast: Incomplete
    bias: Incomplete
    def __init__(self, contrast, bias) -> None: ...
    def __call__(self, values, clip: bool = True, out: Incomplete | None = None): ...
    @property
    def inverse(self):
        """A stretch object that performs the inverse operation."""

class CompositeStretch(CompositeTransform, BaseStretch):
    """
    A combination of two stretches.

    Parameters
    ----------
    stretch_1 : :class:`astropy.visualization.BaseStretch`
        The first stretch to apply.
    stretch_2 : :class:`astropy.visualization.BaseStretch`
        The second stretch to apply.
    """
    def __call__(self, values, clip: bool = True, out: Incomplete | None = None): ...
