from .api import DevicePlacementSpec as DevicePlacementSpec, EnumerableShardingSpec as EnumerableShardingSpec, PlacementSpec as PlacementSpec, ShardingSpec as ShardingSpec, _infer_sharding_spec_from_shards_metadata as _infer_sharding_spec_from_shards_metadata
from torch.distributed._shard.metadata import ShardMetadata as ShardMetadata
