#*===========================================================================
#*  /$$$$$$$$  /$$$$$$  /$$   /$$ /$$$$$$$   /$$$$$$
#* |_____ $$  /$$__  $$| $$  | $$| $$__  $$ /$$__  $$
#*      /$$/ | $$  \__/| $$  | $$| $$  \ $$| $$  \__/
#*     /$$/  |  $$$$$$ | $$$$$$$$| $$$$$$$/| $$
#*    /$$/    \____  $$| $$__  $$| $$__  $$| $$
#*   /$$/     /$$  \ $$| $$  | $$| $$  \ $$| $$    $$
#*  /$$$$$$$$|  $$$$$$/| $$  | $$| $$  | $$|  $$$$$$/
#* |________/ \______/ |__/  |__/|__/  |__/ \______/
#*===========================================================================

#===========================================================================
# *                            ZSH BASICS
#===========================================================================
# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# command execution time stamp shown in the history command output.
HIST_STAMPS="yyyy-mm-dd"

# auto-update behaviour
zstyle ':omz:update' mode auto

# Uncomment the following line to change how often to auto-update (in days).
zstyle ':omz:update' frequency 1

#===========================================================================
# *                            PROMPT
#===========================================================================
eval "$(starship init zsh)"

#===========================================================================
# *                           PLUGINS PREFERENCES
#===========================================================================
# --> autosuggestions
export ZSH_AUTOSUGGEST_STRATEGY=(completion match_prev_cmd history)
export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#ffffff,bg=" #0000ff",bold,underline"

#===========================================================================
# *                         OH-MY-ZSH PLUGINS
#===========================================================================
# Standard plugins: $ZSH/plugins/
# Custom plugins:  $ZSH_CUSTOM/plugins/
plugins=(
    # --> default
    git
    github
    history
    docker
    debian
    battery
    command-not-found
    common-aliases
    copyfile
    copypath
    cp
    colored-man-pages
    colorize
    pip
    python
    ssh
    alias-finder
    aliases
    zsh-navigation-tools
    zsh-interactive-cd
    vscode
    # --> installed via apt
    fzf
    # --> installed via github link
    F-Sy-H
    zsh-autosuggestions
)
source $ZSH/oh-my-zsh.sh
autoload -U compinit && compinit
autoload -U bashcompinit && bashcompinit

#===========================================================================
# *                            FZF
#===========================================================================
# fzf viewing style
export FZF_DEFAULT_OPTS=" --ansi --layout reverse --info inline --border
--preview 'batcat -n --color=always {}'
--bind 'ctrl-/:change-preview-window(down|hidden|)'"
export FZF_DEFAULT_COMMAND='fdfind --hidden --follow --no-ignore --color=always'

# Set up fzf key bindings and fuzzy completion
#   source: https://github.com/junegunn/fzf
source <(fzf --zsh)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
#===========================================================================
# *                            OTHERS (USER CONFIGURATION)
#===========================================================================
# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='code'
else
    export EDITOR='batcat'
fi

#===========================================================================
# *                            BUG FIXES
#===========================================================================
# --- Starship ---
export VIRTUAL_ENV_DISABLE_PROMPT=1

# --- Pylance ---
export NODE_OPTIONS="--max-old-space-size=8192"

#===========================================================================
# *                            Python
#===========================================================================
# uv & uvx completions
eval "$(uv generate-shell-completion zsh)"
eval "$(uvx --generate-shell-completion zsh)"

#===========================================================================
# *                            AUTOGENERATED
#===========================================================================
