def greedy_knapsack(memory: list[float], runtimes: list[float], max_memory: float) -> tuple[float, list[int], list[int]]: ...
def ilp_knapsack(memory: list[float], runtimes: list[float], max_memory: float) -> tuple[float, list[int], list[int]]: ...
def dp_knapsack(memory: list[float], runtime: list[float], max_memory: float) -> tuple[float, list[int], list[int]]: ...
