from _typeshed import Incomplete

_magic_methods: Incomplete

class MockedObject:
    _name: str
    def __new__(cls, *args, **kwargs): ...
    def __init__(self, name: str, _suppress_err: bool) -> None: ...
    def __repr__(self) -> str: ...

def install_method(method_name) -> None: ...
