import torch
from _typeshed import Incomplete
from torch import _prims as _prims
from torch._C import DispatchKey as DispatchKey
from torch._higher_order_ops.utils import autograd_not_implemented as autograd_not_implemented
from torch._ops import HigherOrderOperator as HigherOrderOperator
from torch._prims_common import CUDARngStateHelper as CUDARngStateHelper, make_contiguous_strides_for as make_contiguous_strides_for
from torch._subclasses.fake_tensor import FakeTensorMode as FakeTensorMode
from torch.fx.experimental.proxy_tensor import ProxyTorchDispatchMode as ProxyTorchDispatchMode, disable_proxy_modes_tracing as disable_proxy_modes_tracing, track_tensor_tree as track_tensor_tree
from torch.types import _device as _device, _dtype as _dtype

def throw_on_non_cuda(device) -> None: ...
def register_rng_prim(name, schema, impl_aten, impl_meta, doc, tags=None) -> None: ...
def philox_rand_offset_meta(shape: torch.Size): ...
def philox_rand_offset(shape: torch.Size): ...
def register_philox_rand(): ...
def get_device(args, kwargs): ...
def register_run_and_save_rng_state_op(): ...
def register_run_with_rng_state_op(): ...

run_and_save_rng_state: Incomplete
run_with_rng_state: Incomplete

def register_graphsafe_run_with_rng_state_op(): ...

graphsafe_run_with_rng_state: Incomplete

def register_rng_prims() -> None: ...
