from .common import DeviceOpOverrides as DeviceOpOverrides, register_device_op_overrides as register_device_op_overrides

class MPSDeviceOpOverrides(DeviceOpOverrides):
    def device_guard(self, device_idx: int) -> str: ...
    def set_device(self, device_idx: int) -> str: ...
    def kernel_driver(self) -> str: ...
    def cpp_kernel_type(self) -> str: ...
