from .ns_types import NSNodeTargetType as NSNodeTargetType
from _typeshed import Incomplete
from torch.ao.quantization.backend_config import get_native_backend_config as get_native_backend_config

toq: Incomplete

def get_base_name_to_sets_of_related_ops() -> dict[str, set[NSNodeTargetType]]: ...
def get_base_name_for_op(base_name_to_sets_of_related_ops: dict[str, set[NSNodeTargetType]], op: NSNodeTargetType) -> str | None: ...
def add_op_to_sets_of_related_ops(base_name_to_sets_of_related_ops: dict[str, set[NSNodeTargetType]], op: NSNodeTargetType, related_op: NSNodeTargetType | None) -> None: ...
def get_node_type_to_io_type_map() -> dict[str, set[NSNodeTargetType]]: ...
def get_unmatchable_types_map() -> dict[str, set[NSNodeTargetType]]: ...
