__all__ = ['TWO_OR_MORE_ARGS', 'RETURNS', 'ORIGIN', 'RA_DEC_ORDER']

def TWO_OR_MORE_ARGS(naxis, indent: int = 0): ...
def RETURNS(out_type, indent: int = 0): ...
def ORIGIN(indent: int = 0): ...
def RA_DEC_ORDER(indent: int = 0): ...
