from _typeshed import Incomplete
from astropy import online_docs_root as online_docs_root
from astropy.io.votable import exceptions as exceptions
from astropy.utils.xml.writer import XMLWriter as XMLWriter, xml_escape as xml_escape
from collections.abc import Generator

html_header: str
default_style: str

def make_html_header(w) -> Generator[None]: ...
def write_source_line(w, line, nchar: int = 0) -> None: ...
def write_warning(w, line, xml_lines) -> None: ...
def write_votlint_warning(w, line, xml_lines) -> None: ...
def write_result(result) -> None: ...
def write_result_row(w, result) -> None: ...
def write_table(basename, name, results, root: str = 'results', chunk_size: int = 500) -> None: ...
def add_subset(w, basename, name, subresults, inside=['p'], total: Incomplete | None = None) -> None: ...
def write_index(subsets, results, root: str = 'results') -> None: ...
def write_index_table(root, basename, name, subresults, inside: Incomplete | None = None, total: Incomplete | None = None, chunk_size: int = 500) -> None: ...
