from torch._inductor.autoheuristic.autoheuristic_utils import AHContext as AHContext, AHMetadata as AHMetadata, CHOICE_COL as CHOICE_COL, Choice as Choice
from torch._inductor.autoheuristic.learnedheuristic_interface import LearnedHeuristicRegression as LearnedHeuristicRegression

class PadMMA100(LearnedHeuristicRegression):
    def __init__(self) -> None: ...
    def check_precondition(self, metadata: AHMetadata, context: AHContext) -> bool: ...
    def get_feedback(self, context: AHContext, choice: Choice) -> float: ...
    def get_confidence_threshold(self) -> float: ...
    def get_name(self) -> str: ...
    def predict(self, context: AHContext) -> float: ...
