from typing import Any

class EtcdStubError(ImportError):
    """Custom exception to indicate that the real etcd module is required."""
    def __init__(self) -> None: ...

class EtcdAlreadyExist(Exception):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class EtcdCompareFailed(Exception):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class EtcdKeyNotFound(Exception):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class EtcdWatchTimedOut(Exception):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class EtcdEventIndexCleared(Exception):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class EtcdException(Exception):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class EtcdResult:
    def __init__(self) -> None: ...

class Client:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def read(self, key: str) -> None: ...
    def write(self, key: str, value: Any, ttl: int | None = None, **kwargs: Any) -> None: ...
    def test_and_set(self, key: str, value: Any, prev_value: Any, ttl: int | None = None) -> None: ...
