__all__ = ['system_info']

def system_info() -> None:
    """Print relevant system information for astropy bug reports.

    Examples
    --------
    >>> import astropy
    >>> astropy.system_info()  # doctest: +ELLIPSIS
    platform
    --------
    platform.platform() = ...
    platform.version() = ...
    platform.python_version() = ...
    <BLANKLINE>
    packages
    --------
    astropy              ...
    numpy                ...
    scipy                ...
    matplotlib           ...
    pandas               ...
    pyerfa               ...

    """
