from _typeshed import Incomplete
from torch._C import DispatchKey as DispatchKey
from torch._higher_order_ops.utils import autograd_not_implemented as autograd_not_implemented
from torch._ops import HigherOrderOperator as HigherOrderOperator
from torch._subclasses.fake_tensor import FakeTensorMode as FakeTensorMode
from torch.fx.experimental.proxy_tensor import ProxyTorchDispatchMode as ProxyTorchDispatchMode, track_tensor_tree as track_tensor_tree

class RunConstGraph(HigherOrderOperator):
    def __init__(self) -> None: ...
    def __call__(self, graph, args): ...

run_const_graph: Incomplete

def run_const_graph_dispatch_mode(mode, graph, args): ...
@run_const_graph.py_functionalize_impl
def run_const_graph_functional(ctx, graph, args): ...
def run_const_graph_fake_tensor_mode(mode, graph, args): ...
def run_const_graph_cpu(graph, args): ...
