from torch.distributed._shard.sharded_tensor import ShardedTensor as ShardedTensor, _sharded_op_impl as _sharded_op_impl

def _communicate_result(result, pg): ...
def binary_cmp(cmp_fun, types, args, kwargs=None, process_group=None): ...
def equal(types, args, kwargs, process_group): ...
def allclose(types, args, kwargs, process_group): ...
