from collections.abc import Iterable
from typing import TypeVar

__all__ = ['all', 'any', 'enumerate', 'sum']

_T = TypeVar('_T')

def all(iterable: Iterable[object], /) -> bool: ...
def any(iterable: Iterable[object], /) -> bool: ...
def enumerate(iterable: Iterable[_T], start: int = 0) -> Iterable[tuple[int, _T]]: ...
def sum(iterable: Iterable[_T], /, start: _T = 0) -> _T: ...
