from torch._utils import CallbackRegistry as CallbackRegistry
from typing import Callable

EventCreationCallbacks: CallbackRegistry[int]
EventDeletionCallbacks: CallbackRegistry[int]
EventRecordCallbacks: CallbackRegistry[int, int]
EventWaitCallbacks: CallbackRegistry[int, int]
MemoryAllocationCallbacks: CallbackRegistry[int]
MemoryDeallocationCallbacks: CallbackRegistry[int]
StreamCreationCallbacks: CallbackRegistry[int]
DeviceSynchronizationCallbacks: CallbackRegistry[[]]
StreamSynchronizationCallbacks: CallbackRegistry[int]
EventSynchronizationCallbacks: CallbackRegistry[int]

def register_callback_for_event_creation(cb: Callable[[int], None]) -> None: ...
def register_callback_for_event_deletion(cb: Callable[[int], None]) -> None: ...
def register_callback_for_event_record(cb: Callable[[int, int], None]) -> None: ...
def register_callback_for_event_wait(cb: Callable[[int, int], None]) -> None: ...
def register_callback_for_memory_allocation(cb: Callable[[int], None]) -> None: ...
def register_callback_for_memory_deallocation(cb: Callable[[int], None]) -> None: ...
def register_callback_for_stream_creation(cb: Callable[[int], None]) -> None: ...
def register_callback_for_device_synchronization(cb: Callable[[], None]) -> None: ...
def register_callback_for_stream_synchronization(cb: Callable[[int], None]) -> None: ...
def register_callback_for_event_synchronization(cb: Callable[[int], None]) -> None: ...
