from . import _dtypes_impl as _dtypes_impl, _util as _util
from torch import add as add, arctan2 as arctan2, bitwise_and as bitwise_and, bitwise_or as bitwise_or, bitwise_xor as bitwise_xor, copysign as copysign, divide as divide, float_power as float_power, floor_divide as floor_divide, fmax as fmax, fmin as fmin, fmod as fmod, gcd as gcd, greater as greater, greater_equal as greater_equal, heaviside as heaviside, hypot as hypot, lcm as lcm, ldexp as ldexp, less as less, less_equal as less_equal, logaddexp as logaddexp, logaddexp2 as logaddexp2, logical_and as logical_and, logical_or as logical_or, logical_xor as logical_xor, maximum as maximum, minimum as minimum, multiply as multiply, nextafter as nextafter, not_equal as not_equal, remainder as remainder, subtract as subtract, true_divide as true_divide

def matmul(x, y): ...
def divmod(x, y): ...
