from torch import arccos as arccos, arccosh as arccosh, arcsin as arcsin, arcsinh as arcsinh, arctan as arctan, arctanh as arctanh, bitwise_not as bitwise_not, ceil as ceil, conj_physical as conjugate, cos as cos, cosh as cosh, deg2rad as deg2rad, exp as exp, exp2 as exp2, expm1 as expm1, floor as floor, isfinite as isfinite, isinf as isinf, isnan as isnan, log as log, log10 as log10, log1p as log1p, log2 as log2, logical_not as logical_not, negative as negative, rad2deg as rad2deg, reciprocal as reciprocal, sign as sign, signbit as signbit, sin as sin, sinh as sinh, sqrt as sqrt, square as square, tan as tan, tanh as tanh, trunc as trunc

def cbrt(x): ...
def positive(x): ...
def absolute(x): ...
abs = absolute
conj = conjugate
