from ._normalizations import ArrayLike, normalizer

__all__ = ['seed', 'random_sample', 'sample', 'random', 'rand', 'randn', 'normal', 'choice', 'randint', 'shuffle', 'uniform']

@deco_stream
def seed(seed=None) -> None: ...
@deco_stream
def random_sample(size=None): ...
def rand(*size): ...
sample = random_sample
random = random_sample

@deco_stream
def uniform(low: float = 0.0, high: float = 1.0, size=None): ...
@deco_stream
def randn(*size): ...
@deco_stream
def normal(loc: float = 0.0, scale: float = 1.0, size=None): ...
@deco_stream
def shuffle(x) -> None: ...
@deco_stream
def randint(low, high=None, size=None): ...
@deco_stream
@normalizer
def choice(a: ArrayLike, size=None, replace: bool = True, p: ArrayLike | None = None): ...
