import logging
from .. import config as config
from torch.utils._ordered_set import OrderedSet as OrderedSet

logger: logging.Logger
MAIN_RANDOM_SEED: int

def set_deterministic() -> None:
    """Make torch manual seed deterministic."""
def clean_memory() -> None:
    """Clean memory to avoid OOM."""
def compare_dict_tensors(dict_base, dict_control, precision): ...
def compare_tuple_tensors(tuple_base, tuple_control, precision): ...
def compare_parameters(model_base, model_control, precision): ...
def compare_forward_output(pred_base, pred_control, precision): ...
def compare_gradients(model_base, model_control, precision): ...
def run_model(model_base, model_control, model_input, num_iterations: int = 10, precision: float = 0.0001) -> None: ...
def numeric_check_if_enabled(gm_before_fx_passes, gm_after_fx_passes, example_inputs, num_iterations, precision) -> None: ...
