from _typeshed import Incomplete
from astropy.table import Table as Table

__all__: Incomplete

def io_read(format, filename, **kwargs): ...
def io_write(format, table, filename, **kwargs): ...
def io_identify(suffix, origin, filepath, fileobj, *args, **kwargs): ...
def _get_connectors_table(): ...
