from collections.abc import Sequence
from pathlib import Path

def read_file(fname: Path | str) -> list[str]: ...
def _embed_headers(content: list[str], include_dirs: list[Path], processed_files: set[str]) -> str: ...
def embed_headers(fname: str, include_dirs: Sequence[str] | Sequence[Path] | str | None = None) -> str: ...
