from pathlib import Path

def remove_triton_function_declaration(source_code: str) -> str: ...
def remove_async_compile(source_code: str) -> str: ...
def rename_kernels(source_code: str) -> str: ...
def merge_params(original_params: list[str], new_params: list[str]) -> list[str]: ...
def add_launch_params(original: str, kernel_to_params: dict[str, tuple[str, str]]) -> str: ...
def process_file(input_filename: str, output_filename: str, auto_generate_params: bool = True) -> str: ...
def get_clean_triton(input_path: Path, output_path: Path = ..., auto_generate_params: bool = True):
    """Run experiments and output results to file

    Args:
        input_path (Optional[Path]): Path to inductor generated output codede
        output_path (Optional[Path]): Path to write out the new python file
        auto_generate_params (bool): Whether to automatically generate launch_params if missing
    """
