from _typeshed import Incomplete

DENY_LIST: Incomplete
strip_file_dir: str

def remove_prefix(text, prefix): ...
def write_to_zip(file_path, strip_file_path, zf, prepend_str: str = '') -> None: ...
def main() -> None: ...
