from datetime import timedelta
from torch._C._distributed_rpc import _DEFAULT_INIT_METHOD as _DEFAULT_INIT_METHOD, _DEFAULT_NUM_WORKER_THREADS as _DEFAULT_NUM_WORKER_THREADS, _DEFAULT_RPC_TIMEOUT_SEC as _DEFAULT_RPC_TIMEOUT_SEC, _UNSET_RPC_TIMEOUT as _UNSET_RPC_TIMEOUT

DEFAULT_RPC_TIMEOUT_SEC: float
DEFAULT_INIT_METHOD: str
DEFAULT_SHUTDOWN_TIMEOUT: float
DEFAULT_NUM_WORKER_THREADS: int
DEFAULT_PROCESS_GROUP_TIMEOUT: timedelta
UNSET_RPC_TIMEOUT: float
__all__: list[str]
