from torch._export.db.case import ExportCase as ExportCase, SupportLevel as SupportLevel, _EXAMPLE_CASES as _EXAMPLE_CASES, _EXAMPLE_CONFLICT_CASES as _EXAMPLE_CONFLICT_CASES, _EXAMPLE_REWRITE_CASES as _EXAMPLE_REWRITE_CASES, export_case as export_case

def _collect_examples() -> None: ...
def all_examples(): ...
def get_name(case): ...

msg: str

def filter_examples_by_support_level(support_level: SupportLevel): ...
def get_rewrite_cases(case): ...
