from .registry import register_backend as register_backend
from torch.onnx._internal.onnxruntime import is_onnxrt_backend_supported as is_onnxrt_backend_supported, torch_compile_backend as torch_compile_backend

def has_onnxruntime(): ...
def information_displaying_backend(*args, **kwargs) -> None: ...
