from .frame import RectangularFrame as RectangularFrame
from _typeshed import Incomplete
from matplotlib.text import Text

class AxisLabels(Text):
    _frame: Incomplete
    _minpad: Incomplete
    _visibility_rule: str
    def __init__(self, frame, minpad: int = 1, *args, **kwargs) -> None: ...
    def get_minpad(self, axis): ...
    _visible_axes: Incomplete
    def set_visible_axes(self, visible_axes) -> None: ...
    def get_visible_axes(self): ...
    def set_minpad(self, minpad) -> None: ...
    def set_visibility_rule(self, value) -> None: ...
    def get_visibility_rule(self): ...
    def draw(self, renderer, bboxes, ticklabels_bbox, coord_ticklabels_bbox, ticks_locs, visible_ticks) -> None: ...
