from .ecliptic import BarycentricMeanEcliptic as BarycentricMeanEcliptic, BarycentricTrueEcliptic as BarycentricTrueEcliptic, CustomBarycentricEcliptic as CustomBarycentricEcliptic, GeocentricMeanEcliptic as GeocentricMeanEcliptic, GeocentricTrueEcliptic as GeocentricTrueEcliptic, HeliocentricEclipticIAU76 as HeliocentricEclipticIAU76, HeliocentricMeanEcliptic as HeliocentricMeanEcliptic, HeliocentricTrueEcliptic as HeliocentricTrueEcliptic
from .gcrs import GCRS as GCRS
from .icrs import ICRS as ICRS
from .utils import EQUINOX_J2000 as EQUINOX_J2000, get_jd12 as get_jd12, get_offset_sun_from_barycenter as get_offset_sun_from_barycenter
from astropy.coordinates.baseframe import frame_transform_graph as frame_transform_graph
from astropy.coordinates.errors import UnitsError as UnitsError
from astropy.coordinates.matrix_utilities import matrix_transpose as matrix_transpose, rotation_matrix as rotation_matrix
from astropy.coordinates.transformations import AffineTransform as AffineTransform, DynamicMatrixTransform as DynamicMatrixTransform, FunctionTransformWithFiniteDifference as FunctionTransformWithFiniteDifference

def _mean_ecliptic_rotation_matrix(equinox): ...
def _true_ecliptic_rotation_matrix(equinox): ...
def _obliquity_only_rotation_matrix(obl=...): ...
def gcrs_to_geoecliptic(gcrs_coo, to_frame): ...
def geoecliptic_to_gcrs(from_coo, gcrs_frame): ...
def icrs_to_baryecliptic(from_coo, to_frame): ...
def baryecliptic_to_icrs(from_coo, to_frame): ...

_NEED_ORIGIN_HINT: str

def icrs_to_helioecliptic(from_coo, to_frame): ...
def helioecliptic_to_icrs(from_coo, to_frame): ...
def gcrs_to_true_geoecliptic(gcrs_coo, to_frame): ...
def true_geoecliptic_to_gcrs(from_coo, gcrs_frame): ...
def icrs_to_true_baryecliptic(from_coo, to_frame): ...
def true_baryecliptic_to_icrs(from_coo, to_frame): ...
def icrs_to_true_helioecliptic(from_coo, to_frame): ...
def true_helioecliptic_to_icrs(from_coo, to_frame): ...
def ecliptic_to_iau76_icrs(from_coo, to_frame): ...
def icrs_to_iau76_ecliptic(from_coo, to_frame): ...
def icrs_to_custombaryecliptic(from_coo, to_frame): ...
def custombaryecliptic_to_icrs(from_coo, to_frame): ...
