from .altaz import AltAz as AltAz
from .hadec import HADec as HADec
from .itrs import ITRS as ITRS
from _typeshed import Incomplete
from astropy.coordinates.baseframe import frame_transform_graph as frame_transform_graph
from astropy.coordinates.matrix_utilities import matrix_transpose as matrix_transpose, rotation_matrix as rotation_matrix
from astropy.coordinates.representation import CartesianRepresentation as CartesianRepresentation
from astropy.coordinates.transformations import FunctionTransformWithFiniteDifference as FunctionTransformWithFiniteDifference

CELMIN: float
SELMIN: float
NORTH_POLE: Incomplete

def itrs_to_altaz_mat(lon, lat): ...
def itrs_to_hadec_mat(lon): ...
def altaz_to_hadec_mat(lat): ...
def add_refraction(aa_crepr, observed_frame): ...
def remove_refraction(aa_crepr, observed_frame): ...
def itrs_to_observed(itrs_coo, observed_frame): ...
def observed_to_itrs(observed_coo, itrs_frame): ...
