import dataclasses
import os
import torch
from onnxscript import ir as ir
from torch.onnx._internal.exporter import _analysis as _analysis, _registration as _registration, _verification as _verification

@dataclasses.dataclass
class ExportStatus:
    torch_export_strict: bool | None = ...
    torch_export_non_strict: bool | None = ...
    torch_export_draft_export: bool | None = ...
    decomposition: bool | None = ...
    onnx_translation: bool | None = ...
    onnx_checker: bool | None = ...
    onnx_runtime: bool | None = ...
    output_accuracy: bool | None = ...

def _status_emoji(status: bool | None) -> str: ...
def _format_export_status(status: ExportStatus) -> str: ...
def _strip_color_from_string(text: str) -> str: ...
def _format_exported_program(exported_program: torch.export.ExportedProgram) -> str: ...
def construct_report_file_name(timestamp: str, status: ExportStatus) -> str: ...
def format_decomp_comparison(pre_decomp_unique_ops: set[str], post_decomp_unique_ops: set[str]) -> str:
    """Format the decomposition comparison result.

    Args:
        unique_ops_in_a: The unique ops in the first program.
        unique_ops_in_b: The unique ops in the second program.

    Returns:
        The formatted comparison result.
    """
def format_verification_infos(verification_infos: list[_verification.VerificationInfo]) -> str:
    """Format the verification result.

    Args:
        verification_infos: The verification result.

    Returns:
        The formatted verification result.
    """
def create_torch_export_error_report(filename: str | os.PathLike, formatted_traceback: str, *, export_status: ExportStatus, profile_result: str | None): ...
def create_onnx_export_report(filename: str | os.PathLike, formatted_traceback: str, program: torch.export.ExportedProgram, *, decomp_comparison: str | None = None, export_status: ExportStatus, profile_result: str | None, model: ir.Model | None = None, registry: _registration.ONNXRegistry | None = None, verification_result: str | None = None): ...
