from torch._C._export import pt2_archive_constants as pt2_archive_constants

AOTINDUCTOR_DIR: str
ARCHIVE_FORMAT_PATH: str
ARCHIVE_FORMAT_VALUE: str
ARCHIVE_ROOT_NAME: str
ARCHIVE_VERSION_PATH: str
ARCHIVE_VERSION_VALUE: str
CONSTANTS_DIR: str
CUSTOM_OBJ_FILENAME_PREFIX: str
EXTRA_DIR: str
MODELS_DIR: str
MODELS_FILENAME_FORMAT: str
MODULE_INFO_PATH: str
MTIA_DIR: str
SAMPLE_INPUTS_DIR: str
SAMPLE_INPUTS_FILENAME_FORMAT: str
TENSOR_CONSTANT_FILENAME_PREFIX: str
WEIGHT_FILENAME_PREFIX: str
WEIGHTS_DIR: str
XL_MODEL_WEIGHTS_DIR: str
XL_MODEL_WEIGHTS_PARAM_CONFIG_PATH: str
