from .cirs import CIRS as CIRS
from .gcrs import GCRS as GCRS
from .hcrs import HCRS as HCRS
from .icrs import ICRS as ICRS
from .utils import atciqz as atciqz, aticq as aticq, get_offset_sun_from_barycenter as get_offset_sun_from_barycenter
from astropy.coordinates.baseframe import frame_transform_graph as frame_transform_graph
from astropy.coordinates.erfa_astrom import erfa_astrom as erfa_astrom
from astropy.coordinates.representation import CartesianRepresentation as CartesianRepresentation, SphericalRepresentation as SphericalRepresentation, UnitSphericalRepresentation as UnitSphericalRepresentation
from astropy.coordinates.transformations import AffineTransform as AffineTransform, FunctionTransformWithFiniteDifference as FunctionTransformWithFiniteDifference
from astropy.utils.compat import COPY_IF_NEEDED as COPY_IF_NEEDED

def icrs_to_cirs(icrs_coo, cirs_frame): ...
def cirs_to_icrs(cirs_coo, icrs_frame): ...
def icrs_to_gcrs(icrs_coo, gcrs_frame): ...
def gcrs_to_icrs(gcrs_coo, icrs_frame): ...
def gcrs_to_hcrs(gcrs_coo, hcrs_frame): ...

_NEED_ORIGIN_HINT: str

def hcrs_to_icrs(hcrs_coo, icrs_frame): ...
def icrs_to_hcrs(icrs_coo, hcrs_frame): ...
