from _typeshed import Incomplete

class Equality:
    lhs: Incomplete
    rhs: Incomplete
    def __init__(self, lhs: object, rhs: object) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
