import argparse
from _typeshed import Incomplete
from astropy import __version__ as __version__
from astropy.io import fits as fits
from astropy.io.fits.util import fill as fill

log: Incomplete
DESCRIPTION: Incomplete
EPILOG: Incomplete

class StoreListAction(argparse.Action):
    def __init__(self, option_strings, dest, nargs: Incomplete | None = None, **kwargs) -> None: ...
    def __call__(self, parser, namespace, values, option_string: Incomplete | None = None) -> None: ...

def handle_options(argv: Incomplete | None = None): ...
def setup_logging(outfile: Incomplete | None = None): ...
def match_files(paths): ...
def main(args: Incomplete | None = None): ...
