from _typeshed import Incomplete
from torch._C import _cudnn as _cudnn

def get_cudnn_mode(mode): ...

class Unserializable:
    inner: Incomplete
    def __init__(self, inner) -> None: ...
    def get(self): ...
    def __getstate__(self): ...
    def __setstate__(self, state) -> None: ...

def init_dropout_state(dropout, train, dropout_seed, dropout_state): ...
