from _typeshed import Incomplete

class PythonDispatcher:
    namespace: str
    name: str
    runtime_keys: Incomplete
    alias_keys: Incomplete
    supported_keys: Incomplete
    ref: Incomplete
    def __init__(self) -> None: ...
    def keys(self): ...
    def register(self, dispatchKeys) -> None: ...
    def _format_line(self, key, kernel): ...
    def _format_header(self, header): ...
    def rawRegistrations(self): ...
    def rawDispatchTable(self): ...
    def registrations(self): ...
    def dispatchTable(self): ...
