from _typeshed import Incomplete
from torch._inductor import config as config
from torch._inductor.utils import is_linux as is_linux

log: Incomplete

def _rocm_include_paths(dst_file_ext: str) -> list[str]: ...
def _rocm_lib_options(dst_file_ext: str) -> list[str]: ...
def _rocm_compiler_options() -> list[str]: ...
def rocm_compiler() -> str | None: ...
def rocm_compile_command(src_files: list[str], dst_file: str, dst_file_ext: str, extra_args: list[str] | None = None) -> str: ...
