from _typeshed import Incomplete
from torch.nn.modules.utils import _list_with_default as _list_with_default, _pair as _pair, _quadruple as _quadruple, _single as _single, _triple as _triple

_builtin_table: dict[int, str] | None
_modules_containing_builtins: Incomplete
_builtin_ops: Incomplete

def _gen_torch_functional_registered_ops(): ...

_functional_registered_ops: Incomplete

def _is_special_functional_bound_op(fn): ...
def _get_builtin_table(): ...
def _register_builtin(fn, op) -> None: ...
def _find_builtin(fn): ...
