def build_intlist(data: list[int]) -> list[int]: ...
def build_tensorlist(data: list[object]) -> list[object]: ...
def build_doublelist(data: list[float]) -> list[float]: ...
def build_boollist(data: list[bool]) -> list[bool]: ...
def build_tensor_from_id(data: int | object) -> int | None: ...
def restore_type_tag(value: object, type_str: str) -> object: ...
