from torch._C import _compile_graph_to_code_table as _compile_graph_to_code_table, _generate_upgraders_graph as _generate_upgraders_graph

def format_bytecode(table): ...
def generate_upgraders_bytecode() -> list: ...
