from _typeshed import Incomplete
from torch.jit._builtins import _find_builtin as _find_builtin

def _hidden(name): ...
def _emit_type(type): ...
def _emit_arg(indent, i, arg): ...
def _emit_args(indent, arguments): ...
def _emit_ret(ret): ...
def _emit_rets(returns): ...
def _emit_schema(mod, name, schema, arg_start: int = 0, padding: int = 4): ...
def _get_tensor_ops(): ...
def _get_nn_functional_ops(): ...
def _get_builtins_helper(): ...
def _is_math_fn(fn): ...
def _get_torchscript_builtins(): ...
def _get_math_builtins(): ...
def _get_global_builtins(): ...
def _list_supported_ops(): ...

__doc__: Incomplete
