from _typeshed import Incomplete

NO_DITHER: int
SUBTRACTIVE_DITHER_1: int
SUBTRACTIVE_DITHER_2: int
QUANTIZE_METHOD_NAMES: Incomplete
DITHER_SEED_CLOCK: int
DITHER_SEED_CHECKSUM: int
COMPRESSION_TYPES: Incomplete
DEFAULT_COMPRESSION_TYPE: str
DEFAULT_QUANTIZE_LEVEL: float
DEFAULT_QUANTIZE_METHOD = NO_DITHER
DEFAULT_DITHER_SEED = DITHER_SEED_CLOCK
DEFAULT_HCOMP_SCALE: int
DEFAULT_HCOMP_SMOOTH: int
DEFAULT_BLOCK_SIZE: int
DEFAULT_BYTE_PIX: int
CMTYPE_ALIASES: Incomplete
COMPRESSION_KEYWORDS: Incomplete
