from _typeshed import Incomplete

class simulationresult:
    finish_time: Incomplete
    energy_remaining: Incomplete
    proportion_completed: Incomplete
    velocity_profile: Incomplete
    results: Incomplete
    def __init__(self, finish_time, proportion_completed, energy_remaining, velocity_profile) -> None: ...
    def get_finish_time(self): ...
    def get_proportion_completed(self): ...
    def get_energy_remaining(self): ...
    def get_velocity_profile(self): ...
    def to_string(self): ...
