import functools

def autograd_kernel_indirection(custom_op): ...
def autograd_not_implemented(custom_op): ...
def mark_non_differentiable(ctx, output, output_differentiability) -> None: ...
def construct_autograd_kernel(schema, output_differentiability, custom_op, op_overload, save_for_backward_fn, backward_fn): ...
def gen_autograd_function(name, forward, backward): ...
@functools.lru_cache
def namedtuple_args_cls(schema): ...
def namedtuple_args(schema, args): ...
def validate_grad_inputs_dict(grad_inputs_dict, forward_op, args_info) -> None: ...
def grad_inputs_dict_to_flat_tuple(grad_inputs_dict, args_info): ...
def save_pytree_for_backward(ctx, stuff) -> None: ...
def unpack_saved(ctx): ...
