from typing import Any

NodeMetadataValue = Any
PROTECTED_KEYS: set[str]

class NodeMetadata:
    data: dict[str, Any]
    def __init__(self, data: dict[str, Any]) -> None: ...
    def __getitem__(self, key: str) -> NodeMetadataValue: ...
    def __setitem__(self, key: str, value: NodeMetadataValue) -> NodeMetadataValue: ...
    def __contains__(self, key: str) -> bool: ...
    def copy(self) -> NodeMetadata: ...
