import types
from .utils import ExactWeakKeyDictionary as ExactWeakKeyDictionary
from typing import Any

class CodeContextDict:
    code_context: ExactWeakKeyDictionary
    def __init__(self) -> None: ...
    def has_context(self, code: types.CodeType) -> bool: ...
    def get_context(self, code: types.CodeType) -> dict[str, Any]: ...
    def pop_context(self, code: types.CodeType) -> dict[str, Any]: ...
    def clear(self) -> None: ...

code_context: CodeContextDict
