from torch.fx import Graph as Graph, Node as Node, map_arg as map_arg
from torch.utils._ordered_set import OrderedSet as OrderedSet

def _get_flat_args(node: Node, node_to_additional_deps: dict[Node, OrderedSet[Node]]) -> list[Node]: ...
def _get_flat_args_unique(node: Node, node_to_additional_deps: dict[Node, OrderedSet[Node]]) -> OrderedSet[Node]: ...
def _detect_cycles(graph: Graph, node_to_additional_deps: dict[Node, OrderedSet[Node]]) -> str: ...
