name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
    - name: Check-out the Repository
      uses: actions/checkout@v5
      with:
        persist-credentials: false

    - name: Set-up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.12.9' 
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Create uv Environment
      run: uv venv

    - name: Install Dependencies
      run: uv sync --all-groups

    - name: Install pandoc
      run: sudo apt-get install -y pandoc

    - name: Build HTML
      run: uv run sphinx-build -b html docs docs/_build

    - name: Upload Documentation
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: docs/_build

    - name: Delete _autoapi Folder
      run: rm -rf docs/_autoapi
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      if: github.ref == 'refs/heads/main'
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build
        force_orphan: true