from astropy.utils.exceptions import AstropyWarning

__all__ = ['MergeConflictError', 'MergeConflictWarning']

class MergeConflictError(TypeError): ...
class MergeConflictWarning(AstropyWarning): ...
